# Generated by Django 3.0.6 on 2020-05-17 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('status', models.CharField(max_length=20, verbose_name='상태')),
                ('personnel', models.PositiveIntegerField(verbose_name='최대 인원')),
                ('region', models.CharField(max_length=20, verbose_name='지역')),
                ('goal', models.CharField(max_length=10, verbose_name='목표')),
                ('kind', models.CharField(max_length=40, verbose_name='종류')),
                ('people', models.CharField(max_length=20, verbose_name='사용고객')),
                ('image', models.ImageField(default='default.jpg', upload_to='team/image/%Y/%m/%D/', verbose_name='이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
