# Generated by Django 3.0.6 on 2020-06-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='team',
            name='people',
        ),
        migrations.RemoveField(
            model_name='team',
            name='recruitment_deadline',
        ),
    ]
