# Generated by Django 3.0.6 on 2020-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200627_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='active_status',
            field=models.CharField(choices=[('모집진행중', '모집진행중'), ('활동중', '활동중'), ('활동종료', '활동종료')], default='모집진행중', max_length=15),
        ),
    ]
