# Generated by Django 3.0.6 on 2020-06-01 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_auto_20200528_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_status', models.CharField(choices=[('apr', 'Approved'), ('rjc', 'Rejected'), ('cnc', 'Canceled'), ('wtg', 'Waiting')], default='wtg', max_length=3)),
                ('job', models.CharField(choices=[('dev', 'Developer'), ('pln', 'Planner'), ('dsg', 'Designer')], default='dev', max_length=3)),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='신청생성시간')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='JoinQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer', models.TextField(verbose_name='대답')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.TeamApplication')),
            ],
        ),
    ]
