# Generated by Django 3.0.6 on 2020-06-18 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200619_0705'),
        ('applications', '0002_auto_20200601_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.TextField()),
                ('answer2', models.TextField()),
                ('answer3', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.TeamApplication')),
            ],
        ),
        migrations.CreateModel(
            name='JoinQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.TextField(default='안녕하세요! 간단한 자기소개 부탁드립니다!')),
                ('question2', models.TextField(default='팀에 지원하는 동기는 무엇인가요?')),
                ('question3', models.TextField(default='팀의 어떤 부분에 기여하고 싶으신가요? 다양한 생각을 들려주세요!')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.DeleteModel(
            name='JoinQuestion',
        ),
    ]
