# Generated by Django 3.0.6 on 2020-06-19 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_team_status'),
        ('applications', '0003_auto_20200619_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.TeamApplication')),
            ],
        ),
        migrations.CreateModel(
            name='JoinQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='joinquestions',
            name='team',
        ),
        migrations.DeleteModel(
            name='JoinAnswers',
        ),
        migrations.DeleteModel(
            name='JoinQuestions',
        ),
        migrations.AddField(
            model_name='joinanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.JoinQuestion'),
        ),
    ]
