# Generated by Django 3.0.6 on 2020-07-04 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20200627_2230'),
        ('applications', '0004_auto_20200619_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinquestion',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teams.Team'),
        ),
    ]
