# Generated by Django 3.0.6 on 2020-07-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200704_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinanswer',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.TeamApplication'),
        ),
    ]
