# Generated by Django 3.0.6 on 2020-05-27 20:31

import config.storage_backends
import config.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default_user.png', storage=config.storage_backends.PublicMediaStorage(), upload_to=config.utils.s3_test_image_upload_to, verbose_name='이미지'),
        ),
    ]
