# Generated by Django 3.0.6 on 2020-07-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.TextField(blank=True, null=True),
        ),
    ]
