# Generated by Django 3.0.6 on 2020-07-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_introduce'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_subscribe',
            field=models.BooleanField(default=True),
        ),
    ]
